exports.up = async function (knex) {
  await knex.schema.createTable('todos', function (table) {
    table.increments()
    table.string('description').notNullable() // https://knexjs.org/guide/schema-builder.html#notnullable
    table.datetime('deadline') // https://knexjs.org/guide/schema-builder.html#timestamps
    table.boolean('isComplete').notNullable().defaultTo(false)
    table.integer('userId')
    table.foreign('userId').references('users.id')
    table.timestamps(true, true) // https://knexjs.org/guide/schema-builder.html#timestamps
  })

  await knex('todos').insert([
    { description: 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', deadline: '2023-08-16 12:58:21', isComplete: true, userId: 7 },
    { description: 'Maecenas pulvinar lobortis est.', isComplete: false, userId: 19 },
    { description: 'Donec quis orci eget orci vehicula condimentum.', deadline: '2023-12-08 06:53:44', isComplete: false, userId: 17 },
    { description: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', deadline: '2023-10-15 03:42:15', isComplete: false, userId: 9 },
    { description: 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', deadline: '2023-07-12 19:55:53', isComplete: true, userId: 7 },
    { description: 'Praesent blandit.', deadline: '2023-09-15 23:03:46', isComplete: true, userId: 15 },
    { description: 'In hac habitasse platea dictumst.', isComplete: false, userId: 8 },
    { description: 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', deadline: '2023-02-03 02:56:55', isComplete: false, userId: 6 },
    { description: 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', deadline: '2024-01-13 17:56:54', isComplete: true, userId: 20 },
    { description: 'Cras non velit nec nisi vulputate nonummy.', isComplete: true, userId: 6 },
    { description: 'Aenean sit amet justo.', deadline: '2024-09-08 08:16:14', isComplete: true, userId: 2 },
    { description: 'Nunc nisl.', isComplete: true, userId: 2 },
    { description: 'Duis consequat dui nec nisi volutpat eleifend.', deadline: '2023-03-14 02:10:01', isComplete: false, userId: 16 },
    { description: 'Suspendisse ornare consequat lectus.', deadline: '2024-06-24 02:59:45', isComplete: false, userId: 13 },
    { description: 'In blandit ultrices enim.', deadline: '2024-08-11 00:02:20', isComplete: true, userId: 6 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', isComplete: false, userId: 17 },
    { description: 'Nulla ut erat id mauris vulputate elementum.', deadline: '2023-10-10 10:17:13', isComplete: false, userId: 5 },
    { description: 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', isComplete: true, userId: 20 },
    { description: 'Nulla facilisi.', deadline: '2024-01-11 17:26:49', isComplete: true, userId: 14 },
    { description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', deadline: '2024-01-06 10:50:01', isComplete: true, userId: 19 },
    { description: 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', isComplete: false, userId: 1 },
    { description: 'Maecenas ut massa quis augue luctus tincidunt.', isComplete: true, userId: 9 },
    { description: 'In hac habitasse platea dictumst.', isComplete: false, userId: 6 },
    { description: 'Duis bibendum.', deadline: '2023-08-22 06:17:18', isComplete: true, userId: 2 },
    { description: 'Ut at dolor quis odio consequat varius.', deadline: '2023-04-04 14:18:35', isComplete: true, userId: 10 },
    { description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', deadline: '2024-05-15 08:31:21', isComplete: true, userId: 2 },
    { description: 'Proin risus.', deadline: '2023-12-30 08:42:38', isComplete: false, userId: 6 },
    { description: 'In hac habitasse platea dictumst.', deadline: '2023-05-15 16:05:03', isComplete: true, userId: 7 },
    { description: 'Sed ante.', deadline: '2023-02-22 14:08:50', isComplete: false, userId: 14 },
    { description: 'Suspendisse accumsan tortor quis turpis.', isComplete: false, userId: 16 },
    { description: 'In blandit ultrices enim.', deadline: '2024-07-14 11:22:50', isComplete: false, userId: 5 },
    { description: 'Donec semper sapien a libero.', deadline: '2023-03-09 22:21:26', isComplete: false, userId: 3 },
    { description: 'In congue.', isComplete: true, userId: 4 },
    { description: 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', deadline: '2023-10-16 09:39:33', isComplete: false, userId: 15 },
    { description: 'Nullam varius.', deadline: '2023-01-27 00:21:55', isComplete: true, userId: 3 },
    { description: 'Duis at velit eu est congue elementum.', deadline: '2023-01-16 13:00:01', isComplete: false, userId: 11 },
    { description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', deadline: '2023-04-29 23:29:45', isComplete: true, userId: 14 },
    { description: 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', isComplete: false, userId: 17 },
    { description: 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', isComplete: false, userId: 8 },
    { description: 'Nullam porttitor lacus at turpis.', deadline: '2023-08-25 16:39:16', isComplete: true, userId: 7 },
    { description: 'In hac habitasse platea dictumst.', isComplete: false, userId: 18 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', deadline: '2024-08-11 18:50:34', isComplete: true, userId: 13 },
    { description: 'Vivamus in felis eu sapien cursus vestibulum.', isComplete: true, userId: 6 },
    { description: 'Duis mattis egestas metus.', deadline: '2023-05-26 09:08:02', isComplete: false, userId: 5 },
    { description: 'Proin interdum mauris non ligula pellentesque ultrices.', isComplete: false, userId: 4 },
    { description: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', deadline: '2024-04-12 12:54:53', isComplete: true, userId: 17 },
    { description: 'Vivamus vel nulla eget eros elementum pellentesque.', deadline: '2024-01-02 19:41:25', isComplete: false, userId: 13 },
    { description: 'Etiam vel augue.', deadline: '2023-05-05 15:32:40', isComplete: true, userId: 6 },
    { description: 'Aliquam sit amet diam in magna bibendum imperdiet.', isComplete: true, userId: 13 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', isComplete: false, userId: 8 },
    { description: 'Aliquam quis turpis eget elit sodales scelerisque.', deadline: '2023-12-06 04:44:38', isComplete: false, userId: 1 },
    { description: 'Pellentesque eget nunc.', deadline: '2024-02-17 01:56:18', isComplete: true, userId: 6 },
    { description: 'In hac habitasse platea dictumst.', deadline: '2023-10-10 03:32:20', isComplete: true, userId: 17 },
    { description: 'Donec ut mauris eget massa tempor convallis.', deadline: '2023-04-04 03:19:31', isComplete: false, userId: 14 },
    { description: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', deadline: '2024-08-17 21:47:57', isComplete: true, userId: 4 },
    { description: 'Morbi non quam nec dui luctus rutrum.', isComplete: false, userId: 5 },
    { description: 'In quis justo.', isComplete: true, userId: 4 },
    { description: 'Nunc purus.', isComplete: true, userId: 10 },
    { description: 'Quisque porta volutpat erat.', deadline: '2024-05-31 13:15:36', isComplete: true, userId: 11 },
    { description: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', deadline: '2022-11-20 19:17:38', isComplete: false, userId: 19 },
    { description: 'Quisque id justo sit amet sapien dignissim vestibulum.', isComplete: false, userId: 14 },
    { description: 'Nulla ac enim.', isComplete: false, userId: 18 },
    { description: 'Sed accumsan felis.', isComplete: true, userId: 18 },
    { description: 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', deadline: '2023-06-10 05:24:37', isComplete: false, userId: 20 },
    { description: 'Maecenas rhoncus aliquam lacus.', deadline: '2024-01-19 19:38:52', isComplete: false, userId: 9 },
    { description: 'Duis aliquam convallis nunc.', isComplete: false, userId: 20 },
    { description: 'Etiam pretium iaculis justo.', deadline: '2024-02-20 08:33:58', isComplete: true, userId: 9 },
    { description: 'Suspendisse potenti.', deadline: '2023-11-26 02:44:24', isComplete: true, userId: 11 },
    { description: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', deadline: '2023-12-30 15:08:32', isComplete: true, userId: 14 },
    { description: 'Suspendisse potenti.', deadline: '2023-05-04 04:54:53', isComplete: false, userId: 1 },
    { description: 'In quis justo.', deadline: '2023-03-19 09:35:43', isComplete: false, userId: 7 },
    { description: 'Morbi ut odio.', deadline: '2023-04-27 09:38:10', isComplete: false, userId: 15 },
    { description: 'Aliquam erat volutpat.', isComplete: false, userId: 7 },
    { description: 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', deadline: '2024-06-09 08:26:00', isComplete: false, userId: 19 },
    { description: 'Duis at velit eu est congue elementum.', isComplete: true, userId: 16 },
    { description: 'Pellentesque eget nunc.', deadline: '2023-11-05 15:00:02', isComplete: false, userId: 12 },
    { description: 'Proin eu mi.', isComplete: true, userId: 10 },
    { description: 'Suspendisse accumsan tortor quis turpis.', deadline: '2023-03-23 19:52:40', isComplete: true, userId: 8 },
    { description: 'In congue.', isComplete: false, userId: 8 },
    { description: 'In hac habitasse platea dictumst.', isComplete: true, userId: 12 },
    { description: 'Donec ut dolor.', deadline: '2022-10-08 03:00:47', isComplete: true, userId: 12 },
    { description: 'Duis mattis egestas metus.', deadline: '2023-11-13 17:19:15', isComplete: false, userId: 14 },
    { description: 'Nunc nisl.', deadline: '2023-01-30 11:14:30', isComplete: false, userId: 12 },
    { description: 'In eleifend quam a odio.', deadline: '2023-08-02 03:04:36', isComplete: true, userId: 3 },
    { description: 'Nulla suscipit ligula in lacus.', deadline: '2022-11-08 21:50:14', isComplete: false, userId: 7 },
    { description: 'Nam tristique tortor eu pede.', isComplete: false, userId: 19 },
    { description: 'Integer a nibh.', isComplete: false, userId: 17 },
    { description: 'Nam nulla.', isComplete: false, userId: 8 },
    { description: 'Morbi quis tortor id nulla ultrices aliquet.', deadline: '2022-10-18 05:46:35', isComplete: true, userId: 5 },
    { description: 'Aenean auctor gravida sem.', isComplete: true, userId: 18 },
    { description: 'Duis consequat dui nec nisi volutpat eleifend.', isComplete: false, userId: 8 },
    { description: 'Sed vel enim sit amet nunc viverra dapibus.', deadline: '2023-08-16 05:18:14', isComplete: true, userId: 12 },
    { description: 'Vivamus tortor.', deadline: '2023-01-02 17:29:13', isComplete: false, userId: 9 },
    { description: 'Suspendisse ornare consequat lectus.', isComplete: true, userId: 3 },
    { description: 'In hac habitasse platea dictumst.', deadline: '2023-11-03 02:49:24', isComplete: false, userId: 1 },
    { description: 'Ut at dolor quis odio consequat varius.', isComplete: true, userId: 20 },
    { description: 'Donec ut dolor.', isComplete: false, userId: 17 },
    { description: 'Nullam sit amet turpis elementum ligula vehicula consequat.', deadline: '2023-05-17 04:09:50', isComplete: true, userId: 8 },
    { description: 'Praesent blandit.', isComplete: true, userId: 7 },
    { description: 'Praesent blandit.', deadline: '2022-12-10 01:27:36', isComplete: false, userId: 2 },
    { description: 'Nulla justo.', isComplete: true, userId: 7 },
    { description: 'Proin interdum mauris non ligula pellentesque ultrices.', isComplete: false, userId: 11 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', isComplete: true, userId: 16 },
    { description: 'In sagittis dui vel nisl.', deadline: '2023-06-20 15:41:43', isComplete: true, userId: 1 },
    { description: 'Praesent id massa id nisl venenatis lacinia.', deadline: '2022-09-20 11:14:00', isComplete: true, userId: 10 },
    { description: 'Proin at turpis a pede posuere nonummy.', deadline: '2023-09-28 09:07:30', isComplete: true, userId: 12 },
    { description: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', deadline: '2022-12-15 11:30:45', isComplete: false, userId: 20 },
    { description: 'Praesent blandit lacinia erat.', isComplete: false, userId: 3 },
    { description: 'Nulla suscipit ligula in lacus.', deadline: '2022-09-25 19:34:17', isComplete: false, userId: 2 },
    { description: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', deadline: '2022-11-27 11:05:00', isComplete: false, userId: 13 },
    { description: 'Praesent blandit.', isComplete: true, userId: 15 },
    { description: 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', deadline: '2022-11-03 07:11:20', isComplete: true, userId: 6 },
    { description: 'Nam dui.', deadline: '2024-08-29 16:04:50', isComplete: false, userId: 5 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', deadline: '2024-03-07 02:57:25', isComplete: true, userId: 4 },
    { description: 'Morbi porttitor lorem id ligula.', deadline: '2023-07-12 15:27:46', isComplete: false, userId: 7 },
    { description: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', deadline: '2024-04-15 21:55:24', isComplete: true, userId: 16 },
    { description: 'Vestibulum sed magna at nunc commodo placerat.', deadline: '2023-03-13 06:02:24', isComplete: false, userId: 17 },
    { description: 'Maecenas pulvinar lobortis est.', isComplete: false, userId: 5 },
    { description: 'Duis consequat dui nec nisi volutpat eleifend.', isComplete: true, userId: 11 },
    { description: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', deadline: '2023-01-27 04:43:49', isComplete: false, userId: 4 },
    { description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', deadline: '2022-11-14 08:50:29', isComplete: true, userId: 16 },
    { description: 'Cras non velit nec nisi vulputate nonummy.', isComplete: false, userId: 3 },
    { description: 'Sed ante.', deadline: '2024-05-09 06:17:04', isComplete: false, userId: 7 },
    { description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', deadline: '2024-01-11 06:16:23', isComplete: true, userId: 19 },
    { description: 'Duis ac nibh.', isComplete: true, userId: 6 },
    { description: 'Aenean auctor gravida sem.', isComplete: false, userId: 4 },
    { description: 'Praesent id massa id nisl venenatis lacinia.', isComplete: true, userId: 18 },
    { description: 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', deadline: '2022-12-01 04:42:56', isComplete: false, userId: 17 },
    { description: 'Suspendisse potenti.', deadline: '2023-10-08 01:23:51', isComplete: true, userId: 20 },
    { description: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', deadline: '2022-11-29 18:56:34', isComplete: false, userId: 5 },
    { description: 'Nunc nisl.', deadline: '2022-10-22 01:40:16', isComplete: false, userId: 10 },
    { description: 'Morbi vel lectus in quam fringilla rhoncus.', isComplete: true, userId: 11 },
    { description: 'Proin at turpis a pede posuere nonummy.', deadline: '2023-07-02 03:04:03', isComplete: false, userId: 19 },
    { description: 'Donec ut mauris eget massa tempor convallis.', isComplete: true, userId: 19 },
    { description: 'Nulla justo.', deadline: '2023-04-11 12:50:41', isComplete: false, userId: 17 },
    { description: 'Proin at turpis a pede posuere nonummy.', deadline: '2024-02-04 11:47:58', isComplete: false, userId: 17 },
    { description: 'In blandit ultrices enim.', deadline: '2023-02-28 10:33:20', isComplete: false, userId: 1 },
    { description: 'Duis mattis egestas metus.', deadline: '2024-01-12 10:59:22', isComplete: false, userId: 6 },
    { description: 'Vivamus tortor.', isComplete: true, userId: 4 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', deadline: '2023-12-06 03:30:57', isComplete: false, userId: 19 },
    { description: 'Mauris sit amet eros.', deadline: '2023-03-18 16:49:31', isComplete: false, userId: 13 },
    { description: 'In hac habitasse platea dictumst.', isComplete: true, userId: 8 },
    { description: 'Morbi quis tortor id nulla ultrices aliquet.', isComplete: false, userId: 7 },
    { description: 'Proin eu mi.', deadline: '2022-11-02 14:32:14', isComplete: true, userId: 13 },
    { description: 'Integer a nibh.', isComplete: false, userId: 3 },
    { description: 'In sagittis dui vel nisl.', deadline: '2023-10-31 15:27:13', isComplete: true, userId: 11 },
    { description: 'Etiam vel augue.', isComplete: false, userId: 16 },
    { description: 'Duis bibendum.', deadline: '2023-08-31 04:29:06', isComplete: true, userId: 2 },
    { description: 'Morbi a ipsum.', deadline: '2023-09-28 23:20:28', isComplete: true, userId: 9 },
    { description: 'Maecenas ut massa quis augue luctus tincidunt.', isComplete: false, userId: 1 },
    { description: 'Fusce consequat.', deadline: '2024-01-22 11:25:00', isComplete: true, userId: 4 },
    { description: 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', isComplete: false, userId: 2 },
    { description: 'Donec dapibus.', isComplete: true, userId: 10 },
    { description: 'Donec ut mauris eget massa tempor convallis.', deadline: '2023-06-20 10:29:46', isComplete: false, userId: 10 },
    { description: 'Praesent blandit.', isComplete: true, userId: 8 },
    { description: 'Duis ac nibh.', deadline: '2023-02-24 14:29:32', isComplete: false, userId: 6 },
    { description: 'Phasellus sit amet erat.', isComplete: false, userId: 19 },
    { description: 'Maecenas rhoncus aliquam lacus.', deadline: '2023-06-24 20:09:01', isComplete: false, userId: 15 },
    { description: 'Quisque id justo sit amet sapien dignissim vestibulum.', deadline: '2022-10-23 20:05:48', isComplete: true, userId: 8 },
    { description: 'Pellentesque viverra pede ac diam.', isComplete: true, userId: 15 },
    { description: 'Fusce posuere felis sed lacus.', deadline: '2024-07-11 11:26:55', isComplete: false, userId: 1 },
    { description: 'Integer tincidunt ante vel ipsum.', deadline: '2024-02-19 16:34:46', isComplete: false, userId: 1 },
    { description: 'Maecenas rhoncus aliquam lacus.', deadline: '2023-06-17 20:02:25', isComplete: false, userId: 20 },
    { description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', isComplete: true, userId: 13 },
    { description: 'Pellentesque eget nunc.', deadline: '2023-12-18 23:22:54', isComplete: true, userId: 1 },
    { description: 'Vestibulum rutrum rutrum neque.', isComplete: false, userId: 4 },
    { description: 'Duis ac nibh.', isComplete: true, userId: 2 },
    { description: 'Fusce posuere felis sed lacus.', deadline: '2024-06-03 13:25:05', isComplete: true, userId: 9 },
    { description: 'Sed ante.', isComplete: false, userId: 2 },
    { description: 'Suspendisse potenti.', isComplete: true, userId: 8 },
    { description: 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', deadline: '2024-09-06 21:54:19', isComplete: false, userId: 13 },
    { description: 'Vivamus in felis eu sapien cursus vestibulum.', deadline: '2023-08-15 16:29:19', isComplete: true, userId: 15 },
    { description: 'Cras pellentesque volutpat dui.', deadline: '2023-05-21 06:44:48', isComplete: true, userId: 16 },
    { description: 'Donec dapibus.', isComplete: false, userId: 2 },
    { description: 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', isComplete: true, userId: 1 },
    { description: 'Donec quis orci eget orci vehicula condimentum.', deadline: '2022-12-20 02:15:48', isComplete: true, userId: 14 },
    { description: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', deadline: '2023-09-13 01:08:01', isComplete: false, userId: 3 },
    { description: 'Quisque porta volutpat erat.', isComplete: false, userId: 8 },
    { description: 'Praesent blandit.', isComplete: true, userId: 5 },
    { description: 'In sagittis dui vel nisl.', deadline: '2024-03-28 12:26:21', isComplete: true, userId: 3 },
    { description: 'Praesent blandit.', isComplete: false, userId: 1 },
    { description: 'Duis aliquam convallis nunc.', deadline: '2024-07-02 23:36:27', isComplete: false, userId: 18 },
    { description: 'Morbi ut odio.', isComplete: true, userId: 8 },
    { description: 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', deadline: '2023-04-24 19:58:35', isComplete: true, userId: 15 },
    { description: 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', isComplete: false, userId: 5 },
    { description: 'Curabitur at ipsum ac tellus semper interdum.', isComplete: false, userId: 16 },
    { description: 'Curabitur convallis.', deadline: '2024-01-24 21:20:12', isComplete: true, userId: 9 },
    { description: 'Donec dapibus.', isComplete: false, userId: 4 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', deadline: '2024-07-25 23:57:47', isComplete: true, userId: 20 },
    { description: 'In quis justo.', isComplete: false, userId: 16 },
    { description: 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', deadline: '2023-09-14 16:39:11', isComplete: true, userId: 7 },
    { description: 'Duis consequat dui nec nisi volutpat eleifend.', isComplete: true, userId: 4 },
    { description: 'Morbi non quam nec dui luctus rutrum.', deadline: '2024-07-24 04:23:27', isComplete: false, userId: 12 },
    { description: 'Suspendisse potenti.', deadline: '2023-09-03 15:50:06', isComplete: true, userId: 3 },
    { description: 'Maecenas tincidunt lacus at velit.', deadline: '2023-04-21 13:47:02', isComplete: true, userId: 15 },
    { description: 'Integer tincidunt ante vel ipsum.', deadline: '2023-07-08 08:35:32', isComplete: false, userId: 2 },
    { description: 'Suspendisse potenti.', isComplete: true, userId: 2 },
    { description: 'Vivamus vel nulla eget eros elementum pellentesque.', isComplete: true, userId: 7 },
    { description: 'Morbi quis tortor id nulla ultrices aliquet.', deadline: '2024-01-05 21:18:53', isComplete: false, userId: 18 },
    { description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', deadline: '2022-11-09 07:06:45', isComplete: false, userId: 17 },
  ])
}

exports.down = async function (knex) {
  await knex.schema.dropTable('todos')
}
